version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://backend:5000
    depends_on:
      - backend

  backend:
    build: ./server
    ports:
      - "5000:5000"
    environment:
      - DB_USER=XXX
      - DB_HOST=XXX
      - DB_NAME=postgres
      - DB_PASSWORD=XXX
      - DB_PORT=XXX

# Server settings
PORT=3000
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    ports:
      - "27017:27017"
    volumes:
      - postgres:/data/db

volumes:
  postgres:
